[[tier]]
tasks = ["mu-wfbc"]

[[tier]]
tasks = ["mu-5dj2"]

[[tier]]
tasks = ["mu-eqqv"]

[[tier]]
tasks = ["mu-35z9"]

[[tier]]
tasks = ["mu-943b"]

[[tier]]
tasks = ["mu-hzf9"]

[[tier]]
tasks = ["mu-9dv8"]

[[tier]]
tasks = ["mu-pfgp"]

[[tier]]
tasks = ["mu-mfjg"]

[[tier]]
tasks = ["mu-h848"]
